USE URegBase;

-- Drop Views
DROP VIEW IF EXISTS Regulation_Editorial_Revisions;
DROP VIEW IF EXISTS Regulation_Revisions_Summary;
DROP VIEW IF EXISTS Regulation_Details_Extended;
DROP VIEW IF EXISTS Regulations_Policies_Stakeholders;
DROP VIEW IF EXISTS Regulation_Citations_VIEW;

-- Drop FKs
ALTER TABLE REVISION_PROCESS DROP FOREIGN KEY fk_revision_process_revision_id;
ALTER TABLE REVISION DROP FOREIGN KEY fk_revision_reg_id;
ALTER TABLE REGULATION_STAKEHOLDER DROP FOREIGN KEY fk_reg_stakeholder_id;
ALTER TABLE REGULATION_STAKEHOLDER DROP FOREIGN KEY fk_reg_stakeholder_reg_id;
ALTER TABLE STAKEHOLDER DROP FOREIGN KEY fk_stakeholder_classification_id;
ALTER TABLE REGULATION_CITATION DROP FOREIGN KEY fk_reg_citation_citation_id;
ALTER TABLE REGULATION_CITATION DROP FOREIGN KEY fk_reg_citation_reg_id;
ALTER TABLE CITATION DROP FOREIGN KEY fk_citation_citation_classification_id;
ALTER TABLE CITATION DROP FOREIGN KEY fk_citation_regulation_id;
ALTER TABLE REGULATION DROP FOREIGN KEY fk_reg_classification;
ALTER TABLE REGULATION DROP FOREIGN KEY fk_reg_pol_id;


-- Drop Tables
DROP TABLE IF EXISTS REVISION_PROCESS;
DROP TABLE IF EXISTS REVISION;
DROP TABLE IF EXISTS REGULATION_STAKEHOLDER;
DROP TABLE IF EXISTS STAKEHOLDER;
DROP TABLE IF EXISTS STAKEHOLDER_CLASSIFICATION;
DROP TABLE IF EXISTS REGULATION_CITATION;
DROP TABLE IF EXISTS CITATION;
DROP TABLE IF EXISTS CITATION_CLASSIFICATION;
DROP TABLE IF EXISTS REGULATION;
DROP TABLE IF EXISTS REGULATION_CLASSIFICATION;
DROP TABLE IF EXISTS POLICY;
